# Generated by Django 2.2.7 on 2019-12-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='a_email',
            field=models.CharField(default='personal@gmail.com', max_length=50),
        ),
    ]
