# Generated by Django 2.2.7 on 2019-12-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_student_a_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00-10:00'), ('10:00 - 11:00', '10:00-11:00'), ('11:15 - 12:15', '11:15 - 12:15'), ('12:15 - 1:15', '12:15 - 1:15'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00- 6:00', '4:00- 6:00')], default='10:00 - 11:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2019-11-30'),
        ),
    ]
